### ISSUE TITLE
Obsolete comment in chemacs.el

### ISSUE THREAD

**Issue by whxvd** [plexus/chemacs2#10]
The comment
```
;; this must be here to keep the package system happy, normally you do
;; `package-initialize' for real in your own init.el
;; (package-initialize)
```
in `chemacs.el` is obsolete with Emacs 27. Even if it were not, then it would have to be in `init.el`.

By the way, is Chemacs2 intended to support older Emacs'en, too? Or only Emacs 27 upwards?

**Comment by plexus** [comment]
Fixed in #12.
