### ISSUE TITLE
Questions about setting a default profile, ~/.emacs.default and symlinks

### ISSUE THREAD

**Issue by stormwatch** [plexus/chemacs2#15]
If my `.emacs-profiles.el` contents are:
```elisp
(("centaur" . ((user-emacs-directory . "~/.emacs-profiles.d/centaur-emacs")))
 ("default" . ((user-emacs-direcotry . "~/.emacs.default")))
 ("emacs" . ((user-emacs-directory . "~/.emacs-profiles.d/emacs")))
 ("doom" . ((user-emacs-directory . "~/.emacs-profiles.d/doom-emacs")))
 ("lsp" . ((user-emacs-directory . "~/.emacs-profiles.d/lsp")))
 ("purcell" . ((user-emacs-directory . "~/.emacs-profiles.d/purcell-emacs")))
 ("prelude" . ((user-emacs-directory . "~/.emacs-profiles.d/prelude-emacs")))
 ("scimax" . ((user-emacs-directory . "~/.emacs-profiles.d/scimax")))
 ("spacemacs" . ((user-emacs-directory . "~/.emacs-profiles.d/spacemacs")
                 (env . (("SPACEMACSDIR" . "~/.spacemacs.d"))))))
```

and my `.emacs-profile` contents are:
```
spacemacs
```

1) Do I really need to include a `"default"` entry in `.emacs-profiles`?
2) If so, does the associated value must always be `"~/.emacs.default"`?
3) If so, can `"~/.emacs.default"` be a symlink pointing to "~/.emacs-profiles.d/spacemacs"?

**Comment by AndersonTorres** [comment]
@stormwatch 

1. No. There is no need to have an entry called `default`. There is no such a special meaning in an entry called `default`.

The other questions are therefore prejudiced.

**Comment by plexus** [comment]
Hey, sorry @stormwatch I somehow missed your issue before. "default" does have a special meaning, it's the profile we pick when you don't ask for a specific profile. Apart from that it's the same as any profile, you can point it at whatever config you like.
