### ISSUE TITLE
Can chemacs2 be installed in ~/.config/emacs/ directory?

### ISSUE THREAD

**Issue by AndersonTorres** [plexus/chemacs2#18]
Hello!

From Emacs 27 it is possible to put the config files of Emacs inside the XDG directories, namely, `~/.config/emacs/`. I have tested chemacs and it is working as expected.

Is this an expected behaviour?

**Comment by plexus** [comment]
If emacs looks there for its config then that should work. Is there a problem or did you just want to mention that this works? Would you like to submit an update to the readme so people know they have that choice?

**Comment by AndersonTorres** [comment]
Oh, OK! Can I upload a patch file here, without forking?

[0001-Clarify-that-Chemacs-2-can-be-installed-in-XDG_CONFI.patch.txt](https://github.com/plexus/chemacs2/files/6509511/0001-Clarify-that-Chemacs-2-can-be-installed-in-XDG_CONFI.patch.txt)

**Comment by plexus** [comment]
There's a literal edit button on the README. 

![2021-05-19_191939_Nightly](https://user-images.githubusercontent.com/32212/118856387-2e590f00-b8d7-11eb-84d3-4212af0c6f23.png)

Please have some compassion for project maintainers.

**Comment by AndersonTorres** [comment]
Sorry. I didn't noticed.
