### ISSUE TITLE
Windows support

### ISSUE THREAD

**Issue by alienzj** [plexus/chemacs2#19]
Hi, does chemacs2 support windows ?
Recently, I used chemacs2 on windows, but failed.

**Comment by plexus** [comment]
Hi @alienzj , I've never tested chemacs2 on windows, so it's quite possible it doesn't work. However, if you want people to help you you need to provide sufficient information.

- what's your system like? OS version, emacs version/distribution, shell and terminal you are using, etc. WSL/cygwin/mingw/git bash/cmd.exe?
- how/where did you install chemacs2?
- what steps did you perform?
- what result did you expect from those steps?
- what happened instead?

**Comment by alienzj** [comment]
Hi, @plexus Sorry for later replay.
I install emacs using scoop in windows 10.

- OS version: Microsoft Windows 10 Pro 10.0.19041.964
- Emacs version: GNU Emacs 27.2
- Shell: Powershell
- Terminal: Windows Terminal 1.7.1033.0
- Chemacs2 Installation: ```git clone https://github.com/plexus/chemacs2 C:\Users\alienzj\.emacs.d```
- Steps:
  1. Install Chemacs2: ```git clone https://github.com/plexus/chemacs2 C:\Users\alienzj\.emacs.d```
  2. ```mkdir C:\Users\alienzj\.emacs.d-test```
  3. create a ~/.emacs-profiles.el file, for details see below.
     ```(("default" . ((user-emacs-directory . C:\Users\alienzj\.emacs.default"))))```
  4. start emacs: ``` emacs --debug-init```
 - Output:
```elisp
Debugger entered--Lisp error: (error "Non-hex character used for Unicode escape: s (115)")
  read(#<buffer  *temp*>)
  (progn (insert-file-contents chemacs-profiles-path) (goto-char (point-min)) (read (current-buffer)))
  (unwind-protect (progn (insert-file-contents chemacs-profiles-path) (goto-char (point-min)) (read (current-buffer))) (and (buffer-name temp-buffer) (kill-buffer temp-buffer)))
  (save-current-buffer (set-buffer temp-buffer) (unwind-protect (progn (insert-file-contents chemacs-profiles-path) (goto-char (point-min)) (read (current-buffer))) (and (buffer-name temp-buffer) (kill-buffer temp-buffer))))
  (let ((temp-buffer (generate-new-buffer " *temp*"))) (save-current-buffer (set-buffer temp-buffer) (unwind-protect (progn (insert-file-contents chemacs-profiles-path) (goto-char (point-min)) (read (current-buffer))) (and (buffer-name temp-buffer) (kill-buffer temp-buffer)))))
  (let ((profiles (let ((temp-buffer (generate-new-buffer " *temp*"))) (save-current-buffer (set-buffer temp-buffer) (unwind-protect (progn (insert-file-contents chemacs-profiles-path) (goto-char ...) (read ...)) (and (buffer-name temp-buffer) (kill-buffer temp-buffer))))))) (cdr (assoc chemacs-profile-name profiles)))
  (if (and chemacs--with-profile-value (listp chemacs--with-profile-value)) chemacs--with-profile-value (let ((profiles (let ((temp-buffer (generate-new-buffer " *temp*"))) (save-current-buffer (set-buffer temp-buffer) (unwind-protect (progn ... ... ...) (and ... ...)))))) (cdr (assoc chemacs-profile-name profiles))))
  (defvar chemacs-profile (if (and chemacs--with-profile-value (listp chemacs--with-profile-value)) chemacs--with-profile-value (let ((profiles (let ((temp-buffer ...)) (save-current-buffer (set-buffer temp-buffer) (unwind-protect ... ...))))) (cdr (assoc chemacs-profile-name profiles)))))
  eval-buffer(#<buffer  *load*-460734> nil "c:/Users/alienzj/.emacs.d/chemacs.el" nil t)  ; Reading at buffer position 5162
  load-with-code-conversion("c:/Users/alienzj/.emacs.d/chemacs.el" "c:/Users/alienzj/.emacs.d/chemacs.el" nil t)
  require(chemacs "c:/Users/alienzj/.emacs.d/chemacs.el")
  eval-buffer(#<buffer  *load*> nil "c:/Users/alienzj/.emacs.d/early-init.el" nil t)  ; Reading at buffer position 219
  load-with-code-conversion("c:/Users/alienzj/.emacs.d/early-init.el" "c:/Users/alienzj/.emacs.d/early-init.el" t t)
  load("c:/Users/alienzj/.emacs.d/early-init" noerror nomessage)
  startup--load-user-init-file(#f(compiled-function () #<bytecode 0x1409fc1>))
  command-line()
  normal-top-level()
   ```

Best Regards,
Jie Zhu

**Comment by plexus** [comment]
Seems there might be an issue with your `.emacs-profiles.el`

Here it inserts the contents of `.emacs-profiles.el` into a buffer, then uses the Emacs LISP built-in `read` function to parse the data structure.

``` emacs-lisp
  (progn (insert-file-contents chemacs-profiles-path) (goto-char (point-min)) (read (current-buffer)))
```

But `read` is failing

``` emacs-lisp
Debugger entered--Lisp error: (error "Non-hex character used for Unicode escape: s (115)")
  read(#<buffer  *temp*>)
```

Can you share your `.emacs-profile.el`? You probably have a character in there that confuses emacs.

**Comment by alienzj** [comment]
[Uploading emacs-profiles.el.txt…]()

**Comment by alienzj** [comment]
[emacs-profiles.el.txt](https://github.com/plexus/chemacs2/files/6502833/emacs-profiles.el.txt)

**Comment by plexus** [comment]
"C:\Users\alienzj\.emacs.d-test"

That's not a valid string in emacs lisp, since the slashes will be interpreted as introducing escape sequences. Not sure what will actually work in this case, but you can try to either double them, or replace them with forward slashes.

 "C:\\Users\\alienzj\\.emacs.d-test"

Or

 "C:/Users/alienzj/.emacs.d-test"

Same for the other windows style paths.

**Comment by alienzj** [comment]
Thanks very much. 
The problem is solved by replacing`\` with `/`.

**Comment by daviwil** [comment]
Chemacs is working great for me on Windows!
