### ISSUE TITLE
New Emacs command line argument: init-directory

### ISSUE THREAD

**Issue by krisbalintona** [plexus/chemacs2#41]
Emacs just added an `init-directory` command-line argument.  You can see the commit here: https://git.savannah.gnu.org/cgit/emacs.git/log/?qt=grep&q=init-directory

As far as I can tell, this achieves the same same purpose as Chemacs, right?

**Comment by MooersLab** [comment]
This flag does not seem to be available in Emacs version 28.1. It is available in Emacs 29.1. I have been using it for a week. It is wonderful!

**Comment by plexus** [comment]
This would be good to mention in an "alternatives" section in the readme, see also #51
