### ISSUE TITLE
Command line arguments "leak"

### ISSUE THREAD

**Issue by porras** [plexus/chemacs2#49]
Hi! I'm not sure if this is an issue of chemacs2 or emacs-dashboard (the package I'm having trouble with), but I decided to post it here thinking that you all will be more familiar with the nuances of command line arguments :grimacing: If you think this is a problem of emacs-dashboard, I'll submit it there.

When I run `emacs --profile whatever`, chemacs2 does its thing (and does it well), but the command line arguments stay there in the `command-line-args` variable, as `C-h v` shows:

```
command-line-args is a variable defined in ‘C source code’.

Its value is ("emacs" "--with-profile" "whatever")
```

emacs-dashboard [uses `(< (length command-line-args) 2)`](https://github.com/emacs-dashboard/emacs-dashboard/blob/554dc6fac1362dd6b66318c8250eea8bd63aa92f/dashboard.el#L456) to check if emacs was called to open a file. This check obviously yields the wrong result here. But I'm not sure who's at fault here (and how should it be fixed)

* Should chemacs remove those args from the list [here](https://github.com/plexus/chemacs2/blob/d722459287566e8c91ae077bf3d65966ebece190/chemacs.el#L49-L69)? (happy to give an attempt to a PR if you think this is the case). I _think_ this is the case, because that's what happens with the other _normal_ options that get passed to emacs from the command line (I tried `--maximize` and `-Q`, they do their thing but they don't show up in `command-line-args`)
* Or should emacs-dashboard use `command-line-args-left` instead? Or something else? (happy to report or PR there if you think that's the case)

**Comment by plexus** [comment]
Hey Sergio, long time no see! :smile: 

I think removing them makes sense. I don't see any real downsides, unless someone has set up their own additional logic based on these flags... but we already have a `chemacs-profile` var that people should use instead. (there's always an xkcd isn't there https://xkcd.com/1172/)

**Comment by porras** [comment]
:wave:

**Comment by plexus** [comment]
![aaron_thumbsup](https://user-images.githubusercontent.com/32212/203959108-8340c0b4-50c5-4b44-bc0d-600db3a2576f.jpg)
