### ISSUE TITLE
Add "alternatives" section linking back to with-emacs.sh

### ISSUE THREAD

**Issue by plexus** [plexus/chemacs2#51]
I just learned about https://github.com/alphapapa/with-emacs.sh by @alphapapa, which seems like a great alternative to Chemacs2. They have been so nice as to link back to chemacs2 in their README, I think we should return the favor.

**Comment by RishiKumarRay** [comment]
@plexus so description you want to have in the linking section?

**Comment by plexus** [comment]
I would add an "alternatives" section at the bottom before "license".

**Comment by alphapapa** [comment]
@plexus Thanks.
