### ISSUE TITLE
Why special support for straight?

### ISSUE THREAD

**Issue by whxvd** [plexus/chemacs2#9]
What is the rationale for `straight-p` and `chemacs-load-straight`? Why isn't this something that the user should handle in his (early) init? Why not every other package manger (Borg, ...), too?

`chemacs-load-straight` may try to download a file if it is not yet there. That is highly opinionated.

There must be a very strong reason for supporting it in Chemacs and that should be documented (at least in the source).

**Comment by plexus** [comment]
It's there because I added it.
